version: 2.1
jobs:
  build:
    docker: 
      - image: ubuntu:18.04 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Installing chrome
          command: |
            apt-get update
            apt-get install -y curl apt-transport-https
            curl -sL https://deb.nodesource.com/setup_10.x | bash -
            apt-get install -y nodejs build-essential
            curl -sL https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
            echo "deb https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
            apt-get update
            apt-get install -y google-chrome-stable
            groupadd --system chrome
            useradd --system --create-home --gid chrome --groups audio,video chrome
            mkdir --parents /home/chrome/reports
            chown --recursive chrome:chrome /home/chrome
            chown -R chrome:chrome .
            su - chrome
            # curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            # dpkg -i google-chrome.deb
            # sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
            # rm google-chrome.deb
      - run: npm install
      - run: npm run test