version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:lts-browsers
    steps:
      - checkout # check out the code in the project directory
      - run: echo 'export HINT_TRACKING="on"' >> $BASH_ENV
      - run: npm install
      - run: npm run test
